# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepuser',
            name='userEmail',
            field=models.CharField(default=None, max_length=400),
            preserve_default=False,
        ),
    ]
