# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step_app', '0002_stepuser_useremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepuser',
            name='userEmail',
            field=models.CharField(max_length=100),
        ),
    ]
